version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: point_of_sale
    volumes:
      - ./pos.sql:/docker-entrypoint-initdb.d/pos.sql
    networks:
      - springboot-mysql-net

  springboot-react-app:
    container_name: springboot-react-app
    build:
      context: .
      dockerfile: Dockerfile
      args :
        REACT_APP_API_BASE_URL : http://localhost:8080/api
        REACT_APP_DYNAMIC_BASE_URL : http://localhost:8080/dynamic/
    ports:
      - "8080:8080"  # Spring Boot port
    depends_on:
      - mysqldb
    environment:
      - DB_URL=jdbc:mysql://mysqldb:3306/point_of_sale
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - SERVER_PORT=8080
    networks:
      - springboot-mysql-net
    restart: on-failure

networks:
  springboot-mysql-net:
